### ISSUE TITLE
这个关联表只能用join了吧？

### ISSUE THREAD

**Issue by jiangxiulong** [zoujingli/ThinkLibrary#1]

**Comment by jiangxiulong** [comment]
还能用 User::get(1)   hasOne 这种形式吗

**Comment by zoujingli** [comment]
设计 query 时没考虑用 modal

**Comment by zoujingli** [comment]
事实上，query 已经能足大部分需求，最多业务部分再加一个 service

**Comment by YangYongAn** [comment]
> 还能用 User::get(1) hasOne 这种形式吗

我是这样使用model的
`
        $this->title = '商家列表';
        $query = Shop::with(['trade', 'type']);
        $query = $this->_query($query)->like('shop_name,phone,shop_id');
`

**Comment by zoujingli** [comment]
不支持模型

**Comment by zoujingli** [comment]
新版本已经支持模型

**Comment by YangYongAn** [comment]
支持!
