### ISSUE TITLE
Alioss upload url might be wrong with http in some case.

### ISSUE THREAD

**Issue by y-zh** [zoujingli/ThinkLibrary#9]
In case my web is http locally,  AliossStorage->upload method will return a wrong url with wrong HTTP protocal.  Then endpoint URL of Alioss bucket will be HTTPS always, never be http.

**Comment by zoujingli** [comment]
This relates to your configuration of Aliyun OSS domain names. The official Aliyun interface supports both HTTP and HTTPS protocols.

The design principle for file uploads is that if the client uses HTTP for uploading, the interface should be called using the HTTP protocol. Similarly, if HTTPS is used, the HTTPS protocol should be used to call the interface.

Reference link:  
[https://help.aliyun.com/zh/oss/user-guide/regions-and-endpoints?spm=a2c4g.11186623.help-menu-31815.d_2_0_0.77d27667VHz4FS](https://help.aliyun.com/zh/oss/user-guide/regions-and-endpoints?spm=a2c4g.11186623.help-menu-31815.d_2_0_0.77d27667VHz4FS)

**Comment by y-zh** [comment]
There is a case.  To a service behind LB that removes remove SSL when tranfering,  access from outside is HTTPS ( SSL resides in LB) and local service provides HTTP only.  Then a mix usage of HTTP and HTTPS will occur. That's not allowed in browser.

**Comment by zoujingli** [comment]
You might be asking about the scenario where Nginx is used as a proxy, with HTTPS for external access and HTTP for internal communication. In this case, you can consider adding the HTTPS protocol to the proxy configuration, and the system will automatically recognize it as HTTPS.

![image](https://github.com/user-attachments/assets/eae788ef-aa90-4ec1-a044-a2b0140cffdc)

![image](https://github.com/user-attachments/assets/0a34893a-8453-420c-acaf-0041f7ab2195)

Additionally, the system's backend allows configuring the return URL protocol, which can be enforced to return https://. This way, both HTTP and HTTPS are supported seamlessly.

![image](https://github.com/user-attachments/assets/6c347ce4-2fad-4232-8432-11ddc61b352e)

**Comment by y-zh** [comment]
Yes, that's also my workaround.  but my proposal is to let user decide to use HTTP or HTTPS since there is already a configuration item 'type' to specify protocal.

**Comment by zoujingli** [comment]
Currently, when uploading files to Alibaba Cloud OSS from the backend, the system automatically uses the corresponding API based on the current environment's URL protocol. However, the returned file URL can be configured in the backend. If HTTPS is supported, it is typically configured to return https, as HTTP pages can load HTTPS resources, but HTTPS pages cannot load HTTP resources.

**Comment by y-zh** [comment]
I understand.  Thanks for quick reply.
